name = "shaibya-website"
compatibility_date = "2025-09-10"
compatibility_flags = ["nodejs_compat"]

main = ".open-next/worker.js"
assets = {directory = ".open-next/assets", binding = "ASSETS"}

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true